### PR TITLE
Negative stock restriction bugfix

### PR DESCRIPTION
**Pull request by Assimilator**
Altered logic to include adjustments.
Added an extra unit test to test adjustment restriction.

### CODE REVIEW

**Comment by Assimilator** [comment]
Needs more review

**Comment by andrewmoko** [comment]
@Assimilator Sorry this has taken some time. I will re-open and create a review on upsource!

**Comment by Assimilator** [comment]
@andrewmoko Please don't, I found errors in logic here and will resubmit another PR later today.

**Comment by andrewmoko** [comment]
ok

**Pull request closed without merging**
